services:
  api-mongo-db:
    ports:
      - "${OPEN_DPP_MONGODB_PORT}:${OPEN_DPP_MONGODB_PORT}"
    container_name: api-mongo-db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "${OPEN_DPP_MONGODB_PORT}", "--keyFile", "/etc/mongo/mongo_keyfile"]
    logging:
      options:
        max-size: 1g
    volumes:
      - ./docker/mongo_keyfile:/etc/mongo/mongo_keyfile:ro
      - mongo_db:/data/db
      - mongo_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${OPEN_DPP_MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${OPEN_DPP_MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${OPEN_DPP_MONGODB_DATABASE}
    image: mongo:6.0
    networks:
      - open-dpp-local

  mongo-init:
    image: mongo:6.0
    depends_on:
      - api-mongo-db
    command: >
      bash -c "sleep 10 && mongosh --host api-mongo-db --port ${OPEN_DPP_MONGODB_PORT} -u ${OPEN_DPP_MONGODB_USER} -p ${OPEN_DPP_MONGODB_PASSWORD} --eval 'try { var c = rs.conf(); if (c.members[0].host !== \"localhost:${OPEN_DPP_MONGODB_PORT}\") { c.members[0].host = \"localhost:${OPEN_DPP_MONGODB_PORT}\"; rs.reconfig(c, {force: true}); } } catch (e) { rs.initiate({_id: \"rs0\", members: [{_id: 0, host: \"localhost:${OPEN_DPP_MONGODB_PORT}\"}]}) }'"
    networks:
      - open-dpp-local

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: minio server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${OPEN_DPP_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${OPEN_DPP_S3_SECRET_KEY}
    volumes:
      - minio_data:/data
    ports:
      - "${OPEN_DPP_S3_PORT}:9000" # MinIO API
      - "9001:9001" # MinIO Console (Web UI)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - open-dpp-local

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 ${OPEN_DPP_S3_ACCESS_KEY} ${OPEN_DPP_S3_SECRET_KEY};
      /usr/bin/mc mb myminio/${OPEN_DPP_S3_DEFAULT_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${OPEN_DPP_S3_DEFAULT_BUCKET};
      /usr/bin/mc mb myminio/${OPEN_DPP_S3_PROFILE_PICTURE_BUCKET} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${OPEN_DPP_S3_PROFILE_PICTURE_BUCKET};
      /usr/bin/mc version enable myminio/${OPEN_DPP_S3_DEFAULT_BUCKET};
      /usr/bin/mc version enable myminio/${OPEN_DPP_S3_PROFILE_PICTURE_BUCKET};
      exit 0;
      "
    networks:
      - open-dpp-local

  clamav-rest:
    image: ajilaag/clamav-rest
    ports:
      - ${OPEN_DPP_CLAMAV_PORT}:9000
    networks:
      - open-dpp-local

  mailpit:
    container_name: mailpit
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "8026:1025"
    environment:
      - MP_SMTP_AUTH=${OPEN_DPP_MAIL_MAILPIT_SMTP_AUTH}
      - MP_SMTP_AUTH_ALLOW_INSECURE=${OPEN_DPP_MAIL_MAILPIT_SMTP_ALLOW_INSECURE}
    networks:
      - open-dpp-local

volumes:
  caddy_data:
  caddy_config:
  minio_data:
  mongo_db:
  mongo_config:
  api_db:

networks:
  open-dpp-local:
