services:
  mcp-server-test:
    image: ghcr.io/open-dpp/mcp-server:main
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3002:3000"
    environment:
      - PORT=3000

volumes:
  api_db_test:
  mongo_db_test:
  mongo_config_test: